lumelProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lumel_app.urls', namespace='lumel_app')),
]

lumel_app/urls.py
from django.urls import path
from .views import MainView, ArticleListView, ArticleDetailView, LegalsView

app_name = 'lumel_app'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path("actualites/", ArticleListView.as_view(), name='actualites'),
    path("actualites/<int:pk>", ArticleDetailView.as_view(), name='detail-actualite'),
    path("legals/", LegalsView.as_view(), name='legals'),
]

lumel_app/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Article(models.Model):
    titre = models.CharField(max_length=200)
    auteur = models.CharField(max_length=50)
    date = models.DateField()
    contenu = RichTextField()

    def __str__(self):
        return self.titre

lumel_app/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from datetime import time


class CustomTimeInput(forms.TimeInput):
    def format_value(self, value):
        if isinstance(value, time):
            return value.strftime('%H:%M')
        return value


class ContactForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    nom = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Nom'}))
    telephone = forms.CharField(required=False, max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Téléphone'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'E-mail'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Message', 'rows': 4, 'cols': 40}))

lumel_app/views.py
from django.views.generic import DetailView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.core.mail import send_mail
from django.core.mail import BadHeaderError
from django.conf import settings
from django.urls import reverse_lazy
from .forms import ContactForm
from django.http import HttpResponse
from .models import Article


class MainView(FormView):
    template_name = "main.html"
    form_class = ContactForm
    success_url = reverse_lazy('lumel_app:main')

    def form_valid(self, form):
        form_data = form.cleaned_data
        message = f"Nom: {form_data['nom']}\nTéléphone: {form_data['telephone']}\nEmail: {form_data['email']}\nMessage: {form_data['message']}"
        try:
            send_mail(
                'Nouveau message de contact via lumel-associees.fr',
                message,
                settings.EMAIL_HOST_USER,
                ['lumel-associees@outlook.fr', 'jrouscilles@ardc.fr'],
                fail_silently=False,
            )
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        except Exception as e:
            return HttpResponse(f'Error: {e}')

        return super().form_valid(form)


class LegalsView(TemplateView):
    template_name = "legals.html"

class ArticleListView(ListView):
    template_name = "articles.html"
    model = Article


class ArticleDetailView(DetailView):
    template_name = "article.html"
    model = Article

lumel_app/templates/article.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Actualités{% endblock %}

{% block section %}
    <div id="id_article" class="container-fluid yellow-lumel-bg pt-5">
        <div class="lumel-container">
                <h4>{{ object.titre }}</h4>
                <i>{{ object.date }}</i>
                <p>{{ object.contenu|safe }}</p>
        </div>
    </div>
{% endblock %}

lumel_app/templates/articles.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Actualités{% endblock %}
{% block meta_title %}Actualités - Lumel Associées{% endblock %}
{% block meta_ogtitle %}Actualités - Lumel Associées{% endblock %}
{% block canonical_url %}https://www.lumel-associees.fr/actualites{% endblock %}

{% block section %}
    <div id="id_actualites" class="container-fluid yellow-lumel-bg blue-lumel pt-5">
        <div class="lumel-container">
            <h3 class="pb-5">Actualités</h3>
            {% for object in object_list %}
                <h4>{{ object.titre }}</h4>
                <i>{{ object.auteur }}, {{ object.date }}</i>
                <p>{{ object.contenu|truncatechars:500|safe }}</p>
                <a href="{% url 'lumel_app:detail-actualite' object.pk %}">Lire plus</a>
                <hr class="mt-5"/>
            {% endfor %}
        </div>
    </div>
{% endblock %}

lumel_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      <!-- META -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <meta name="title" content="{% block meta_title %}{% endblock %}">
    <meta name="author" content="Lumel & Associées">
    <meta name="description" content="Cabinet d'avocates à Paris 2, alliant modernité et transparence, dédié à défendre vos droits avec éthique et expertise dans tous vos enjeux juridiques.">
    <link rel="canonical" href="{% block canonical_url %}{% endblock %}">
    <meta name="robots" content="index, follow">
    <meta name="keywords" content="avocat, avocates, droit, cabinet, paris, 2, commercial, corporel, social, immobilier, patrimonial, expertise, modernité, transparence, éthique, expertise, juridique, lumel, associées">
    <meta name="theme-color" content="#292E5E">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.lumel-associees.fr/">
    <meta property="og:title" content="{% block meta_ogtitle %}{% endblock %}">
    <meta property="og:description" content="Cabinet d'avocates à Paris 2, alliant modernité et transparence, dédié à défendre vos droits avec éthique et expertise dans tous vos enjeux juridiques.">
    <meta property="og:image" content="{% static 'lumel_app/img/portrait-duo.jpeg' %}">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:locale" content="fr_FR">
    <meta property="og:site_name" content="Lumel & Associées">


    <title>{% block title %}{% endblock %}</title>
    


    <link rel="shortcut icon" type="image/png" href="{% static 'lumel_app/img/favicon.png' %}">


    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-PJF5C2BK');</script>
      <!-- End Google Tag Manager -->

    <!-- LIBS-->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <link href="{% static 'lumel_app/css/libs/aos.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    <script type="text/javascript" src="{% static 'lumel_app/js/libs/lozad.js' %}"></script>
    <script src="{% static 'lumel_app/js/libs/aos.js' %}" defer></script>

      <!-- END LIBS-->


    <!-- MAIN CSS-->
    <link rel="stylesheet" href="{% static 'lumel_app/css/root.css' %}">
    <link rel="stylesheet" href="{% static 'lumel_app/css/styles.css' %}">


    {% block head %}{% endblock %}
</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PJF5C2BK"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    {% include "navbar.html" %}
    {% block section %}{% endblock %}
    {% include "footer.html" %}
    {% block js %} {% endblock %}

    <!-- Axel JS -->
    <script src="{% static 'lumel_app/js/app.js' %}"></script>
    <!-- END AXEL JS-->
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>
</html>

lumel_app/templates/footer.html
{% load static %}

<footer class="container-fluid orange-lumel-bg yellow-lumel pb-5">
    <div class="row pt-5 pb-5 custom-padding-bottom">
        <div class="col-6 col-sm-6 col-md-3">
            <div class="img-container">
                <img src="{% static 'lumel_app/img/logo-jaune.png' %}" alt="Logo" width="200">
            </div>
        </div>
        <div class="col-6 col-sm-6 col-md-9 flex items-end">
            <ul class="footer-list uppercase">
                <li>
                    <a class="footer-link" href="{% url 'lumel_app:main' %}#id_cabinet">Cabinet</a>
                </li>
                <li>
                    <a class="footer-link" href="{% url 'lumel_app:main' %}#id_expertises">Expertises</a>
                </li>
                <li>
                    <a class="footer-link" href="{% url 'lumel_app:actualites' %}">Actualités</a>
                </li>
                <li>
                    <a class="footer-link" href="{% url 'lumel_app:main' %}#id_honoraires">Honoraires</a>
                </li>
                <li>
                    <a class="footer-link" href="{% url 'lumel_app:main' %}#id_contact">Contact</a>
                </li>
                <li>
                    <a class="footer-link" href="{% url 'lumel_app:legals' %}">Mentions Légales</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

<!-- Div fixée en bas de l'écran et visible uniquement sur mobile -->
<div class="d-sm-none fixed-bottom text-white text-center py-2 d-flex d-flex justify-content-around mobile__bottom__contact">
    <a href="tel:+33954953754" class="btn btn-custom-1 rounded-pill px-4 bg-transparent yellow-lumel">09.54.95.37.54</a>
    <a href="{% url 'lumel_app:main' %}#id_contact" class="btn btn-custom-2 rounded-pill px-5 blue-lumel">Contact</a>
</div>

lumel_app/templates/formulaire.html
{% load crispy_forms_tags %}

<form method="post">
    {% csrf_token %}
    <div class="row justify-content-between">
        <div class="col-md-6">
            {{ form.nom|as_crispy_field }}
        </div>
        <div class="col-md-6">
            {{ form.telephone|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            {{ form.email|as_crispy_field }}
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            {{ form.message|as_crispy_field }}
        </div>
    </div>

    <div class="row justify-content-end">
        <div class="col-auto">
            <button type="submit" class="btn btn-custom mt-3">Envoyer</button>
        </div>
    </div>
</form>

lumel_app/templates/legals.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Lumel Associées{% endblock %}

{% block section %}

<section id="legals" class="yellow-lumel-bg py-8">
<div class="legals__content" data-aos="fade-up">
    <h2 class="font-bold">Mentions l&eacute;gales</h2>
    <p><br></p>
    <p>L&rsquo;acc&egrave;s au site <a href="https://www.lumel-associees.fr">https://www.lumel-associees.fr</a> (&laquo; le Site &raquo;) ainsi que l&rsquo;utilisation et la consultation de son contenu, s&rsquo;effectuent dans le cadre des mentions l&eacute;gales et CGU d&eacute;crites ci-apr&egrave;s.</p>
    <p>&nbsp;</p>
    <p>&Eacute;diteur du site&nbsp;: LUMEL ASSOCIEES - Association d&apos;avocats &agrave; responsabilit&eacute; professionnelle individuelle</p>
    <p>&Eacute;tablissement principal&nbsp;: 26, rue L&eacute;opold Bellan &ndash; 75002 Paris</p>
    <p>N&deg; SIREN : 979 211 075</p>
    <p>N&deg; TVA : FR71979211075</p>
    <p>Adresse email : <a href="mailto:contact@lumel-associees.fr">contact@lumel-associees.fr</a></p>
    <p>Directrice de la publication&nbsp;:</p>
    <p>Ma&icirc;tre Lucile QU&Eacute;NET&nbsp;</p>
    <p>H&eacute;bergeur du site&nbsp;:</p>
    <p>GoDaddy.com, LLC</p>
    <p>2155 E GoDaddy Way, Tempe, Arizona 85284, United States</p>
    <p>EU MOSS&nbsp;: EU372022452</p>
    <p>&nbsp;</p>
    <h3 class="font-bold">Les avocates exer&ccedil;ant au sein de l&rsquo;association sont&nbsp;:</h3>
    <ul>
        <li>Maitre Marianne Carbonnel, avocate fran&ccedil;aise inscrite au Barreau de Paris (associ&eacute;e),</li>
        <li>Maitre Lucile Qu&eacute;net, avocate fran&ccedil;aise inscrite au Barreau de Paris (associ&eacute;e).</li>
    </ul>
    <p>&nbsp;</p>
    <h3 class="font-bold">Cr&eacute;dits&nbsp;:</h3>
    <ul>
        <li>Webdesign&nbsp;: Marius Turpin, Malaury Lema&icirc;tre &amp; Axel Durand</li>
        <li>Logo : Marius Turpin&nbsp;</li>
        <li>Photos (portraits de l&rsquo;&eacute;quipe) : Pauline Gouablin</li>
    </ul>
    <p>&nbsp;</p>

    <h3 class="font-bold">Propri&eacute;t&eacute; intellectuelle&nbsp;:</h3>
    <p>L&rsquo;ensemble des marques, logos, signes, illustrations, textes, bases de donn&eacute;es, interfaces, architecture, codes sources, et plus g&eacute;n&eacute;ralement, tout &eacute;l&eacute;ment, mat&eacute;riel ou immat&eacute;riel, figurant sur ou composant le Site (ci-apr&egrave;s&nbsp;&laquo;&nbsp;les &Eacute;l&eacute;ments prot&eacute;g&eacute;s&nbsp;&raquo;) peuvent &ecirc;tre prot&eacute;g&eacute;s par des droits de propri&eacute;t&eacute; intellectuelle d&eacute;tenus par LUMEL ASSOCIEES ou ses partenaires.</p>
    <p>Les utilisateurs du Site s&rsquo;interdisent donc, sans l&rsquo;accord expr&egrave;s pr&eacute;alable de LUMEL ASSOCIEES, et sous peine de poursuites judiciaires, toute reproduction, repr&eacute;sentation, diffusion, adaptation, utilisation, transmission et t&eacute;l&eacute;chargement de l&rsquo;un quelconque des &Eacute;l&eacute;ments prot&eacute;g&eacute;s du site, y compris d&eacute;sassemblages, d&eacute;compilations, d&eacute;cryptages, extractions, t&eacute;l&eacute;chargement, r&eacute;utilisation, copies, en tout ou partie, sur tout support, et par tout proc&eacute;d&eacute;, connu ou inconnu &agrave; ce jour.</p>
    <p>&nbsp;</p>

    <h3 class="font-bold">Responsabilit&eacute;&nbsp;:</h3>
    <p>Le contenu des mentions l&eacute;gales peut &agrave; tout moment faire l&rsquo;objet de mises &agrave; jour. Les &eacute;ventuelles modifications qui en r&eacute;sultent sont alors applicables d&egrave;s leur mise en ligne ; il est donc recommand&eacute; d&rsquo;en v&eacute;rifier r&eacute;guli&egrave;rement la teneur.&nbsp;</p>
    <p>Chaque utilisateur est seul responsable de l&rsquo;utilisation et de la consultation qu&rsquo;il fait du contenu du Site. LUMEL ASSOCIEES s&rsquo;efforce de v&eacute;rifier l&rsquo;exactitude des informations mentionn&eacute;es sur le Site. Toutefois, LUMEL ASSOCIEES n&rsquo;offre aucune garantie, expresse ou tacite, concernant le contenu du Site.</p>
    <p>LUMEL ASSOCIEES ne saurait &ecirc;tre tenue responsable des dommages subis par l&rsquo;utilisateur suite &agrave; l&rsquo;utilisation et &agrave; la consultation du Site et de ses contenus. Cette limitation de responsabilit&eacute; s&rsquo;&eacute;tend &agrave; tous les pr&eacute;judices directs ou indirects, mat&eacute;riels, financiers, informatiques, immat&eacute;riels, cons&eacute;cutifs &agrave; l&rsquo;acc&egrave;s, l&rsquo;usage ou la consultation du Site et des sites Internet li&eacute;s.</p>
    <p>De m&ecirc;me, les liens hypertextes pr&eacute;sent&eacute;s sur le site en direction de ressources ext&eacute;rieures ne sauraient engager la responsabilit&eacute; de LUMEL ASSOCIEES.</p>
</div>
</section>
{% endblock %}

lumel_app/templates/navbar.html
{% load static %}
<div class="container-fluid blue-lumel-bg d-flex align-items-center yellow-lumel">

    <!-- Bloc de contact avec marge à droite -->
    <div class="contact-info d-none d-md-flex align-items-center ms-auto me-5">
        <a href="https://maps.google.com/?q=26+rue+L%C3%A9opold+Bellan+75002+Paris" target="_blank"
           class="text-decoration-none yellow-lumel">
            <p class="pt-3">26 rue Léopold Bellan 75002 </p>
        </a>
        <svg width="50" height="50"> <!-- Taille du SVG -->
            <line x1="10" y1="50" x2="30" y2="1" stroke="#F6EFA0" stroke-width="2"/>
        </svg>
        <a href="tel:+33954953754" target="_blank"
           class="text-decoration-none yellow-lumel me-1">09.54.95.37.54</a>  (9h00 – 19h00) 
    </div>
</div>

<header class="navbar navbar-expand-md navbar-light blue-lumel yellow-lumel-bg">
    <div class="container-fluid">
        <div class="d-flex align-items-center nav-div">
            <a class="me-sm-auto logo-top d-flex align-items-center" href="/">
                <!-- Affichage conditionnel de l'image du logo selon la taille de l'écran -->
                <img src="{% static 'lumel_app/img/logo-bleu.png' %}" alt="Logo" width="200" class="desktop-logo">
                <img src="{% static 'lumel_app/img/logo-jaune.png' %}" alt="Logo" width="100"
                     class="mobile-logo d-none">

            </a>
            <span class="font-bold d-none d-sm-block link">Cabinet Avocates à PARIS 2</span>

            <!-- Bouton hamburger pour mobile -->
            <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>


        <!-- Contenu de la navbar -->
        <nav class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lumel_app:main' %}#id_commercial">Droit Commercial</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lumel_app:main' %}#id_corporel">Dommage corporel</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Autres expertises
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'lumel_app:main' %}#id_social">Droit social</a></li>
                        <li><a class="dropdown-item" href="{% url 'lumel_app:main' %}#id_immobilier">Droit immobilier</a></li>
                        <!-- Ajoute d'autres expertises ici -->
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="btn btn-navbar text-white font-semibold nav-btn"
                       href="{% url 'lumel_app:main' %}#id_contact" role="button">
                        Contact
                    </a>
                </li>


            </ul>
        </nav>
    </div>
</header>